[repository]
name = "Lattice Official"
updated = 1_766_274_026

[p."services.audio"]
p = "services/audio"
d = [ "shared.log", "kernel.device_manager" ]

  [[p."services.audio".f]]
  n = "init.lua"
  s = "a3becdc83e6f533017c6939fb8052a5632944382d1013e5ab10f78fbf4b7e7e1"

[p."services.debug"]
p = "services/debug"
d = [ "shared.log", "kernel.device_manager" ]

  [[p."services.debug".f]]
  n = "init.lua"
  s = "5beda69bb3052af57e61461397624777823cf4fa5e5e01f0eb35939fa1ffb99f"

[p."kernel.core"]
p = "kernel/core"
d = [
  "shared.log",
  "shared.toml",
  "kernel.device_manager",
  "services.debug",
  "services.audio"
]

  [[p."kernel.core".f]]
  n = "init.lua"
  s = "21a00d85ba81c12d548a3b775108e2c33c79d1e590b403fd88861b1c753ad4f4"

[p."kernel.device_manager"]
p = "kernel/device_manager"
d = [ "shared.toml", "shared.log" ]

  [[p."kernel.device_manager".f]]
  n = "init.lua"
  s = "064d0656ddbce75d13177dfcc326f0623c8af946b5d1c79b6d6aac33c62c4475"

[p."packages.os"]
p = "packages/os"
f = [ ]
d = [
  "boot.lboot",
  "boot.startup",
  "kernel.core",
  "kernel.device_manager",
  "config.system",
  "config.repo",
  "packages.core_drivers"
]

[p."packages.core_drivers"]
p = "packages/core_drivers"
f = [ ]
d = [ "drivers.core.monitor", "drivers.core.speaker" ]

[p."packages.kernel"]
p = "packages/kernel"
f = [ ]
d = [
  "kernel.device_manager",
  "kernel.core",
  "config.system",
  "config.repo",
  "packages.core_drivers"
]

[p."packages.shared"]
p = "packages/shared"
f = [ ]
d = [
  "shared.toml",
  "shared.sha2",
  "shared.nanoid",
  "shared.log",
  "shared.hardware_surveyor"
]

[p."packages.boot"]
p = "packages/boot"
f = [ ]
d = [ "boot.hardware_surveyor", "boot.lboot", "boot.startup" ]

[p."config.repo"]
p = "config/repo"

  [[p."config.repo".f]]
  n = "repo.toml"
  s = "a51ac55bc8b7f57fe8a954e80bddc0576d71caa5ab2b758d39817b794348b80c"

  [p."config.repo".m]
  install_path = "/os/repo.toml"

[p."config.system"]
p = "config/system"

  [[p."config.system".f]]
  n = "system.toml"
  s = "81df8e5e663bd71433b451ad75e1e5c5d447811ee7f9f2ae32e04451910f79da"

  [p."config.system".m]
  install_path = "/os/lattice.toml"

[p."shared.toml"]
p = "shared/toml"

  [[p."shared.toml".f]]
  n = "init.lua"
  s = "0c90b91259d676dc21319faba76a60bb1fba4097bdae77847e82ba444be192f1"

[p."shared.nanoid"]
p = "shared/nanoid"

  [[p."shared.nanoid".f]]
  n = "init.lua"
  s = "2641bfaf9e80b1d6dbc0d79431d21663d10904cd3fe0ba606245b31d0c4e42c9"

[p."shared.sha2"]
p = "shared/sha2"

  [[p."shared.sha2".f]]
  n = "init.lua"
  s = "1efccd26c9c423c13143b51c8aa3cd5ae436c0560fe87a04754eca22b1090942"

[p."shared.log"]
p = "shared/log"

  [[p."shared.log".f]]
  n = "init.lua"
  s = "32931972905b1dd71161db0d5da40fde41961085158e3305f32f046510e63fdc"

[p."shared.hardware_surveyor"]
p = "shared/hardware_surveyor"

  [[p."shared.hardware_surveyor".f]]
  n = "init.lua"
  s = "38d9b798f6a2aae9b935fed171e939e210ceafd86a3b4d89e22c285603a4c7af"

[p."bin.mesh"]
p = "bin/mesh"
d = [ "shared.sha2" ]

  [[p."bin.mesh".f]]
  n = "mesh.lua"
  s = "b7e5f3f66f751a4e3ff7369899e776c4805a95b14b978aa71f7551c73e688346"

  [p."bin.mesh".m]
  install_path = "/bin/mesh.lua"

[p."boot.lboot"]
p = "boot/lboot"
d = [ "shared.log", "shared.toml", "kernel.device_manager" ]

  [[p."boot.lboot".f]]
  n = "init.lua"
  s = "c0f382ede7e14adef42fe8668e79ec413d6bd186bb1ef7219e74fef4f8dcd50b"

[p."boot.startup"]
p = "boot/startup"

  [[p."boot.startup".f]]
  n = "init.lua"
  s = "463ff46b2807cb304523b1b4f139473bd55f0b9f14280f75871baea0a8c4123f"

  [p."boot.startup".m]
  install_path = "/startup.lua"

[p."boot.hardware_surveyor"]
p = "boot/hardware_surveyor"
d = [ ]

  [[p."boot.hardware_surveyor".f]]
  n = "init.lua"
  s = "e008643bdfea273ea1ecd3658edabe3c5a7e9625dd00f1f6fa7e525ff2a3a3eb"

[p."drivers.core.printer"]
p = "drivers/core/printer"
t = [ "printer" ]

  [[p."drivers.core.printer".f]]
  n = "init.lua"
  s = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[p."drivers.core.speaker"]
p = "drivers/core/speaker"
d = [ "shared.log" ]
t = [ "speaker" ]

  [[p."drivers.core.speaker".f]]
  n = "init.lua"
  s = "9ba913ce3ad5a838487463c863452d15b2705af0b2433eca752fa1aacad8c4ae"

[p."drivers.core.modem"]
p = "drivers/core/modem"
t = [ "modem" ]

  [[p."drivers.core.modem".f]]
  n = "init.lua"
  s = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[p."drivers.core.monitor"]
p = "drivers/core/monitor"
t = [ "monitor" ]

  [[p."drivers.core.monitor".f]]
  n = "init.lua"
  s = "fad9671697e2ba0b745c780fcff82b7f1b31936d6ca55f166d4168fd62fd92d2"
