[repository]
name = "Lattice Official"
updated = 1_766_598_143

[p."services.audio"]
p = "services/audio"
d = [ "shared.log", "kernel.device_manager" ]

  [[p."services.audio".f]]
  n = "init.lua"
  s = "0cdb263610e691fed3b98c7c0ebbb5e28e15ba461a3bdf36f884dfb50b86875f"

[p."services.debug"]
p = "services/debug"
d = [ "shared.log", "kernel.device_manager" ]

  [[p."services.debug".f]]
  n = "init.lua"
  s = "f5956c20c448b0c7391a848e929e594e84b066192bbb9aa4e4a341a3da04a4d1"

[p."kernel.core"]
p = "kernel/core"
d = [
  "shared.log",
  "shared.toml",
  "kernel.device_manager",
  "services.debug",
  "services.audio"
]

  [[p."kernel.core".f]]
  n = "init.lua"
  s = "21622d06f86d8e12f9503a473b5cf681f0fee7dd4da2f972d25c9225db129205"

[p."kernel.device_manager"]
p = "kernel/device_manager"
d = [ "shared.toml", "shared.log" ]

  [[p."kernel.device_manager".f]]
  n = "init.lua"
  s = "064d0656ddbce75d13177dfcc326f0623c8af946b5d1c79b6d6aac33c62c4475"

[p."packages.os"]
p = "packages/os"
f = [ ]
d = [
  "boot.lboot",
  "boot.startup",
  "kernel.core",
  "kernel.device_manager",
  "config.system",
  "config.repo",
  "packages.core_drivers",
  "packages.shared"
]

[p."packages.core_drivers"]
p = "packages/core_drivers"
f = [ ]
d = [
  "drivers.core.monitor",
  "drivers.core.speaker",
  "drivers.core.disk_drive",
  "drivers.core.modem",
  "drivers.core.computer",
  "drivers.core.printer"
]

[p."packages.kernel"]
p = "packages/kernel"
f = [ ]
d = [
  "kernel.device_manager",
  "kernel.core",
  "config.system",
  "config.repo",
  "packages.core_drivers"
]

[p."packages.shared"]
p = "packages/shared"
f = [ ]
d = [
  "shared.toml",
  "shared.sha2",
  "shared.nanoid",
  "shared.log",
  "shared.hardware_surveyor",
  "shared.sounds"
]

[p."packages.boot"]
p = "packages/boot"
f = [ ]
d = [ "boot.hardware_surveyor", "boot.lboot", "boot.startup" ]

[p."config.repo"]
p = "config/repo"

  [[p."config.repo".f]]
  n = "repo.toml"
  s = "a51ac55bc8b7f57fe8a954e80bddc0576d71caa5ab2b758d39817b794348b80c"

  [p."config.repo".m]
  install_path = "/os/repo.toml"

[p."config.system"]
p = "config/system"

  [[p."config.system".f]]
  n = "system.toml"
  s = "81df8e5e663bd71433b451ad75e1e5c5d447811ee7f9f2ae32e04451910f79da"

  [p."config.system".m]
  install_path = "/os/lattice.toml"

[p."shared.toml"]
p = "shared/toml"

  [[p."shared.toml".f]]
  n = "init.lua"
  s = "0c90b91259d676dc21319faba76a60bb1fba4097bdae77847e82ba444be192f1"

[p."shared.nanoid"]
p = "shared/nanoid"

  [[p."shared.nanoid".f]]
  n = "init.lua"
  s = "2641bfaf9e80b1d6dbc0d79431d21663d10904cd3fe0ba606245b31d0c4e42c9"

[p."shared.sounds"]
p = "shared/sounds"

  [[p."shared.sounds".f]]
  n = "boot.dfpwm"
  s = "3a5d943429d7bb0e5666322d480e5333e0eaaf9be5e46531171fe0a863c9ad8b"

  [p."shared.sounds".m]
  install_path = "/lib/shared/sounds"

[p."shared.sha2"]
p = "shared/sha2"

  [[p."shared.sha2".f]]
  n = "init.lua"
  s = "ee423708b4e1fb200c64a003c0c46e01dbdae2773205983b52a238ae7652f3da"

[p."shared.log"]
p = "shared/log"

  [[p."shared.log".f]]
  n = "init.lua"
  s = "32931972905b1dd71161db0d5da40fde41961085158e3305f32f046510e63fdc"

[p."shared.hardware_surveyor"]
p = "shared/hardware_surveyor"

  [[p."shared.hardware_surveyor".f]]
  n = "init.lua"
  s = "38d9b798f6a2aae9b935fed171e939e210ceafd86a3b4d89e22c285603a4c7af"

[p."bin.mesh"]
p = "bin/mesh"
d = [ "shared.sha2" ]

  [[p."bin.mesh".f]]
  n = "mesh.lua"
  s = "6a4ee705d13d3db2010d53c669201512bb0e17b169a6465a053c9114cfd38e3f"

  [p."bin.mesh".m]
  install_path = "/bin/mesh.lua"

[p."boot.lboot"]
p = "boot/lboot"
d = [ "shared.log", "shared.toml", "kernel.device_manager" ]

  [[p."boot.lboot".f]]
  n = "init.lua"
  s = "c0f382ede7e14adef42fe8668e79ec413d6bd186bb1ef7219e74fef4f8dcd50b"

[p."boot.startup"]
p = "boot/startup"

  [[p."boot.startup".f]]
  n = "init.lua"
  s = "463ff46b2807cb304523b1b4f139473bd55f0b9f14280f75871baea0a8c4123f"

  [p."boot.startup".m]
  install_path = "/startup.lua"

[p."boot.hardware_surveyor"]
p = "boot/hardware_surveyor"
d = [ ]

  [[p."boot.hardware_surveyor".f]]
  n = "init.lua"
  s = "e008643bdfea273ea1ecd3658edabe3c5a7e9625dd00f1f6fa7e525ff2a3a3eb"

[p."drivers.core.printer"]
p = "drivers/core/printer"
t = [ "printer" ]

  [[p."drivers.core.printer".f]]
  n = "init.lua"
  s = "fb776c9bbf34cf1aa15a377800d8b27b871993a597c93acd9e9ec64b8cdeb14a"

[p."drivers.core.computer"]
p = "drivers/core/computer"
t = [ "computer" ]

  [[p."drivers.core.computer".f]]
  n = "init.lua"
  s = "cc7dd62cf49ef57391fa1fe8feb51f53daa328bb9288cc260eea462a2dba0cbd"

[p."drivers.core.speaker"]
p = "drivers/core/speaker"
d = [ "shared.log" ]
t = [ "speaker" ]

  [[p."drivers.core.speaker".f]]
  n = "init.lua"
  s = "725608277bf4f0b35df7a9331f4fbf4dbe3c7dc82d732c3b5f5627f61254764e"

[p."drivers.core.modem"]
p = "drivers/core/modem"
t = [ "modem" ]

  [[p."drivers.core.modem".f]]
  n = "init.lua"
  s = "7a394efae42e9a41e6ae5789a9a6580901cde0dab9263ef72763ed9fbfa00302"

[p."drivers.core.disk_drive"]
p = "drivers/core/disk_drive"
t = [ "drive" ]

  [[p."drivers.core.disk_drive".f]]
  n = "init.lua"
  s = "31a600fa330dc1bf807e7888b9c6e3696766532f43ccb1438c8aafa756ae72ce"

[p."drivers.core.monitor"]
p = "drivers/core/monitor"
t = [ "monitor" ]

  [[p."drivers.core.monitor".f]]
  n = "init.lua"
  s = "fad9671697e2ba0b745c780fcff82b7f1b31936d6ca55f166d4168fd62fd92d2"
